services:
  api:
    image: job-coach-api
    restart: unless-stopped
    build:
      context: .
#      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/job_coach
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
  celery_worker:
    restart: unless-stopped
    build:
      context: .
#      dockerfile: Dockerfile.dev
    command: celery -A job_coach.app.core.celery:celery_app worker -l info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/job_coach
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started

  postgres:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: job_coach
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: unless-stopped
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    restart: unless-stopped
    image: qdrant/qdrant:v1.12.6
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  qdrant_data:
